### ISSUE TITLE
Fails on Alpine Linux

### ISSUE THREAD

**Issue by deuszx** [trailofbits/dylint#528] opened 2022-12-20 08:38 UTC
Hey team 👋 
I'm not 100% sure this is an issue for `dylint`, or even a bug, but have to start somewhere:

I'm trying to build as small as possible docker image to build contracts for Substrate using `cargo-contract`. I'm starting with `rust:1.65.0-alpine`, installing all the required dependencies:

```sh
/code # rustup show
Default host: x86_64-unknown-linux-musl
rustup home:  /usr/local/rustup

installed toolchains
--------------------

nightly-2022-10-10-x86_64-unknown-linux-musl
nightly-x86_64-unknown-linux-musl
1.65.0-x86_64-unknown-linux-musl (default)

active toolchain
----------------

1.65.0-x86_64-unknown-linux-musl (default)
rustc 1.65.0 (897e37553 2022-11-02)

```
but when I try to build the contract `cargo contract check`, I'm getting:
```sh
/code # cargo contract check
 [1/2] Checking ink! linting rules
Error: command failed: "rustup" "which" "rustc"
stdout: ""
stderr: "error: target triple in channel name 'nightly-2022-06-30-x86_64-unknown-linux-musl'\n"
ERROR: `"/usr/local/rustup/toolchains/1.65.0-x86_64-unknown-linux-musl/bin/cargo" "dylint" "--lib" "ink_linting" "--manifest-path=/code/Cargo.toml"` failed with exit code: Some(1)
```

and for completion:
```sh
/code # rustup which rustc
/usr/local/rustup/toolchains/1.65.0-x86_64-unknown-linux-musl/bin/rustc
```

Any pointers will be really appreciated! Thanks

**Comment by smoelius** [comment] 2022-12-20 11:58
Hi, @deuszx. I haven't used `cargo contract`. But that error looks like it could be caused by an invalid `rust-toolchain` file.

For example, if I create a dummy crate with the following `rust-toolchain` file and try to `cargo build` it, I get an error similar to yours:
```toml
[toolchain]
channel = "nightly-2022-06-30-x86_64-unknown-linux-musl"
```
If I change the channel to just `nightly-2022-06-30`, the error goes a away.

Could this apply to your situation?

If it does, please tell me where the `rust-toolchain` file resides, as it could be Dylint is using the wrong one.

**Comment by deuszx** [comment] 2022-12-21 13:31
Hey @smoelius ,

Thanks for the quick response 🙇‍♂️ I thought that setting default via `rustup default` CLI command would be equivalent to having the `rust-toolchain` file 🤔 

This gets me passed my original error though (and on to the new one) so, again, thank you :)

**Comment by deuszx** [comment] 2022-12-22 10:16
Update: 

I've got:
```sh
> cargo contract check
[1/2] Checking ink! linting rules
If you don't see a backtrace below, it could be because `cargo-dylint` wasn't built with a nightly compiler.
Error: command failed: "rustup" "which" "rustc"
stdout: ""
stderr: "error: target triple in channel name 'nightly-2022-06-30-x86_64-unknown-linux-gnu'\n"

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: dylint_internal::command::Command::output
   2: dylint_internal::rustup::toolchain_path
   3: dylint::driver_builder::get
   4: dylint::run_with_name_toolchain_map
   5: dylint::run
   6: cargo_dylint::main
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: std::rt::lang_start::{{closure}}
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/core/src/ops/function.rs:286:13
  10: std::panicking::try::do_call
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:464:40
  11: std::panicking::try
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:428:19
  12: std::panic::catch_unwind
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panic.rs:137:14
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/rt.rs:148:48
  14: std::panicking::try::do_call
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:464:40
  15: std::panicking::try
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:428:19
  16: std::panic::catch_unwind
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panic.rs:137:14
  17: std::rt::lang_start_internal
             at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/rt.rs:148:20
  18: main
  19: __libc_start_main
  20: _start
ERROR: `"/usr/local/rustup/toolchains/nightly-2022-10-10-x86_64-unknown-linux-gnu/bin/cargo" "dylint" "--lib" "ink_linting" "--manifest-path=/code/Cargo.toml"` failed with exit code: Some(1)
```
even though my `rust-toolchain` looks like this:
```sh
> cat rust-toolchain
[toolchain]
channel = "nightly-2022-10-10"
```

**Comment by smoelius** [comment] 2022-12-22 12:06
This is very strange given that the channel in your `rust-toolchain` file isn't even a prefix of the one on the `stderr` line.

What happens if you run `rustup which rustc` directly?

**Comment by smoelius** [comment] 2022-12-22 16:09
Dropping this here, since it's possibly relevant: https://internals.rust-lang.org/t/priority-of-directory-override-and-rust-toolchain-file/13224

**Comment by smoelius** [comment] 2024-01-25 18:21
@deuszx Were you ever able to determine the cause of this issue?

**Comment by smoelius** [comment] 2024-05-15 13:44
@deuszx It looks like there was a problem related to running Dylint on Alpine Linux. It had to do with use of `musl` and how Dylint constructs `RUSTFLAGS` when building drivers.

However, the bug is now fixed, and we have [a test](https://github.com/trailofbits/dylint/blob/master/tests/alpine/tests/alpine.rs) to verify that Dylint builds and and runs and Alpine Linux.

So I am going to close this issue. But you are welcome to reopen it if you think it is not resolved.

Thanks very much for opening the issue.

**Closed by smoelius** 2024-05-15 13:44 UTC
